name: Test_and_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with: {java-version: 1.8}
     - name: Build release APK after test
       run: |
         ./gradlew test
         ./gradlew assembleRelease
         ./gradlew bundleRelease
     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-debug.apk
         path: app/build/outputs/apk/debug/app-debug.apk
